# Only enable PR builds.
trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: python app/main.py
  displayName: 'Run app and collect metrics'

#- script: python pymetrics/render_graphs.py _pymetrics
#  displayName: 'Render metrics graphs'
#
#- task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: _metrics 
#    artifactName: metrics
#  displayName: 'Publish metrics graphs as build artifact'

#- script: python pymetrics/post_to_github.py _pymetrics
#  displayName: 'Post metrics graphs as PR comment'