trigger: ['master']

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: env
  displayName: env

- script: pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: python app/main.py
  env:
    METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
  displayName: 'Run app and collect metrics'

- script: mkdir _pymetrics
  displayName: 'Make output directory'

- script: python pymetrics/plot.py
  env:
    METRICS_MONGO_CONNECTION: $(METRICS_MONGO_CONNECTION)
  displayName: 'Plot metrics'

# This step is only run on Pull Request
- script: python pymetrics/github_pr.py
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
  displayName: 'Post metrics graphs as PR comment'
  condition: eq(variables['Build.Reason'], 'PullRequest')

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: _pymetrics
    artifactName: metrics
  displayName: 'Publish metrics graphs as build artifact'


